'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { BookOpen, Brain, ChevronRight, Flame, GraduationCap, Headphones, Home, Mic2, RotateCcw, Search, Sparkles, Trophy } from 'lucide-react'
import AccountMenu from '@/components/AccountMenu'
import AudioButton from '@/components/AudioButton'
import ExerciseDeck, { ExerciseResultMeta } from '@/components/ExerciseDeck'
import LessonFlow from '@/components/LessonFlow'
import SpeechPractice from '@/components/SpeechPractice'
import TutorChat from '@/components/TutorChat'
import { exercises, lessons, vocabulary } from '@/data/seed'
import { buildAdaptiveRecommendation, buildAdaptiveReviewDeck } from '@/lib/adaptive-curriculum'
import { CloudSession, ensureProfile, loadCloudProgress, loadSession, mergeProgress, saveCloudProgress } from '@/lib/cloud-sync'
import { defaultProgress, loadProgress, queueTransfers, recordAttempt, registerMistake, saveProgress, scheduleReview, updateMastery } from '@/lib/storage'
import { Exercise, UserProgress } from '@/types'

type Tab='home'|'lesson'|'review'|'speak'|'vocab'|'progress'
const nav:{id:Tab;label:string;icon:any}[]=[{id:'home',label:'Start',icon:Home},{id:'lesson',label:'Lektionen',icon:BookOpen},{id:'review',label:'Wiederholen',icon:RotateCcw},{id:'speak',label:'Sprechen',icon:Mic2},{id:'vocab',label:'Vokabeln',icon:Brain},{id:'progress',label:'Fortschritt',icon:Trophy}]

export default function Page(){
 const [tab,setTab]=useState<Tab>('home'),[progress,setProgress]=useState<UserProgress>(defaultProgress),[lessonId,setLessonId]=useState(1)
 const [session,setSession]=useState<CloudSession|null>(null),[profileId,setProfileId]=useState<string|null>(null),[syncState,setSyncState]=useState('nur lokal')
 const hydrated=useRef(false),syncTimer=useRef<any>(null)
 useEffect(()=>{setProgress(loadProgress());setSession(loadSession());hydrated.current=true},[])
 useEffect(()=>{if(hydrated.current)saveProgress(progress)},[progress])
 useEffect(()=>{if(!session){setProfileId(null);setSyncState('nur lokal');return}let cancelled=false;(async()=>{try{setSyncState('verbinde …');const profile=await ensureProfile(session);if(cancelled)return;setProfileId(profile.id);const cloud=await loadCloudProgress(session,profile.id);if(cancelled)return;if(cloud){const merged=mergeProgress(loadProgress(),cloud);setProgress(merged);saveProgress(merged)}setSyncState('synchronisiert')}catch(e){console.error(e);setSyncState('offline – lokal gespeichert')}})();return()=>{cancelled=true}},[session])
 useEffect(()=>{if(!session||!profileId||!hydrated.current)return;clearTimeout(syncTimer.current);syncTimer.current=setTimeout(async()=>{try{setSyncState('synchronisiere …');await saveCloudProgress(session,profileId,progress);setSyncState('synchronisiert')}catch(e){console.error(e);setSyncState('offline – lokal gespeichert')}},900);return()=>clearTimeout(syncTimer.current)},[progress,session,profileId])
 const activeLesson=Math.min(5,Math.max(1,[...progress.completedLessons,0].sort((a,b)=>b-a)[0]+1))
 function finishLesson(id:number){const ids=vocabulary.filter(v=>v.lesson===id).map(v=>v.id);setProgress(p=>({...p,completedLessons:Array.from(new Set([...p.completedLessons,id])),wordsLearned:Array.from(new Set([...p.wordsLearned,...ids]))}));setTab('progress')}
 function startAdaptive(){const rec=buildAdaptiveRecommendation(progress,exercises,vocabulary,activeLesson);if(rec.kind==='review'||rec.kind==='strengthen')setTab('review');else if(rec.kind==='speaking')setTab('speak');else{setLessonId(rec.lessonId||activeLesson);setTab('lesson')}}
 return <main className="min-h-screen pb-24 md:pb-8"><div className="mx-auto max-w-6xl px-4 py-5 md:px-8 md:py-8"><Header streak={progress.streak} session={session} syncState={syncState} onSession={setSession}/><div className="mt-6 grid gap-6 md:grid-cols-[220px_1fr]"><aside className="hidden md:block"><DesktopNav tab={tab} setTab={setTab}/></aside><section>{tab==='home'&&<HomeView progress={progress} activeLesson={activeLesson} onContinue={startAdaptive} onGo={setTab}/>} {tab==='lesson'&&<LessonArea lessonId={lessonId} setLessonId={setLessonId} progress={progress} setProgress={setProgress} finishLesson={finishLesson}/>} {tab==='review'&&<ReviewView progress={progress} setProgress={setProgress}/>} {tab==='speak'&&<SpeakView setProgress={setProgress}/>} {tab==='vocab'&&<VocabView progress={progress}/>} {tab==='progress'&&<ProgressView progress={progress} cloud={Boolean(session)} syncState={syncState}/>}</section></div></div><MobileNav tab={tab} setTab={setTab}/></main>
}
function Header({streak,session,syncState,onSession}:{streak:number;session:CloudSession|null;syncState:string;onSession:(s:CloudSession|null)=>void}){return <header className="flex items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[0.24em] text-lime-700">Slovensko</div><h1 className="text-xl font-black tracking-tight sm:text-2xl">Slowenisch, das du wirklich sprichst.</h1></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full bg-white px-3 py-2 shadow-soft sm:flex"><Flame size={18}/><span className="font-bold">{streak}</span><span className="text-sm text-slate-500">Tage</span></div><AccountMenu session={session} syncState={syncState} onSession={onSession}/></div></header>}
function DesktopNav({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <nav className="sticky top-6 space-y-1 rounded-3xl bg-white p-3 shadow-soft">{nav.map(n=><button key={n.id} onClick={()=>setTab(n.id)} className={`flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left font-semibold ${tab===n.id?'bg-lime-200 text-slate-950':'text-slate-600 hover:bg-slate-50'}`}><n.icon size={19}/>{n.label}</button>)}</nav>}
function MobileNav({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <nav className="fixed bottom-0 left-0 right-0 z-50 grid grid-cols-6 border-t border-slate-200 bg-white/95 px-1 py-2 backdrop-blur md:hidden">{nav.map(n=><button key={n.id} onClick={()=>setTab(n.id)} className={`flex flex-col items-center gap-1 text-[10px] font-semibold ${tab===n.id?'text-lime-700':'text-slate-500'}`}><n.icon size={20}/>{n.label}</button>)}</nav>}
function HomeView({progress,activeLesson,onContinue,onGo}:{progress:UserProgress;activeLesson:number;onContinue:()=>void;onGo:(t:Tab)=>void}){const due=progress.reviews.filter(r=>r.dueAt<=Date.now()).length,weak=Object.values(progress.mastery||{}).filter(m=>m.attempts>=2&&m.score<.58).length,rec=buildAdaptiveRecommendation(progress,exercises,vocabulary,activeLesson);return <div className="space-y-6"><div className="overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-soft md:p-8"><div className="max-w-2xl"><div className="mb-2 text-sm font-semibold text-lime-300">Dein adaptiver Lernplan</div><h2 className="text-3xl font-black md:text-5xl">Heute genau das, <span className="text-lime-300">was dir am meisten bringt.</span></h2><p className="mt-4 max-w-xl text-slate-300">Die App berücksichtigt jetzt auch Antworttempo und Hilfenutzung.</p><button onClick={onContinue} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-lime-300 px-5 py-3 font-black text-slate-950">Empfehlung starten <ChevronRight/></button></div></div><div className="card border-2 border-lime-200"><div className="flex items-center gap-2 text-sm font-bold text-lime-700"><Sparkles size={18}/>Heute empfohlen</div><h3 className="mt-2 text-2xl font-black">{rec.title}</h3><p className="mt-2 text-slate-600">{rec.reason}</p><div className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">Priorität {rec.priority}</div></div><div className="grid gap-3 sm:grid-cols-4"><Metric icon={Brain} value={`${progress.wordsLearned.length} / 120`} label="Aktiver Wortschatz"/><Metric icon={RotateCcw} value={String(due)} label="Heute fällig"/><Metric icon={Sparkles} value={String(weak)} label="Schwache Bereiche"/><Metric icon={GraduationCap} value={`${progress.completedLessons.length} / 5`} label="Lektionen"/></div><div className="grid gap-4 lg:grid-cols-2"><div className="card"><div className="text-sm font-bold text-lime-700">Manuell weiterlernen</div><h3 className="mt-1 text-xl font-black">Lektion {activeLesson}: {lessons[activeLesson-1]?.title}</h3><p className="mt-2 text-slate-600">Der lineare Kurs bleibt jederzeit verfügbar.</p></div><div className="card"><h3 className="font-black">So entscheidet die App</h3><div className="mt-4 space-y-2 text-sm text-slate-600"><div>1. Fällige Wiederholungen</div><div>2. Grammatik-Transfer nach Fehlern</div><div>3. Schwache oder noch langsame Inhalte</div><div>4. Aktive Produktion</div><div>5. Danach neuer Stoff</div></div></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Quick icon={RotateCcw} label="Wiederholen" onClick={()=>onGo('review')}/><Quick icon={Mic2} label="Sprechen" onClick={()=>onGo('speak')}/><Quick icon={Brain} label="Vokabeln" onClick={()=>onGo('vocab')}/><Quick icon={Trophy} label="Fortschritt" onClick={()=>onGo('progress')}/></div></div>}
function Metric({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="card"><Icon className="mb-3" size={20}/><div className="text-2xl font-black">{value}</div><div className="text-sm text-slate-500">{label}</div></div>}
function Quick({icon:Icon,label,onClick}:{icon:any;label:string;onClick:()=>void}){return <button onClick={onClick} className="card flex min-h-28 flex-col items-start justify-between text-left"><Icon/><span className="font-bold">{label}</span></button>}
function LessonArea({lessonId,setLessonId,progress,setProgress,finishLesson}:{lessonId:number;setLessonId:(id:number)=>void;progress:UserProgress;setProgress:(f:any)=>void;finishLesson:(id:number)=>void}){return <div className="space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{lessons.map(l=><button key={l.id} onClick={()=>setLessonId(l.id)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${lessonId===l.id?'bg-slate-950 text-white':'bg-white text-slate-600'}`}>Lektion {l.id}{progress.completedLessons.includes(l.id)?' ✓':''}</button>)}</div><LessonFlow key={lessonId} lessonId={lessonId} progress={progress} setProgress={setProgress} onExerciseResult={(e,c,m)=>handleExercise(e,c,m,setProgress)} onFinish={()=>finishLesson(lessonId)}/></div>}
function ReviewView({progress,setProgress}:{progress:UserProgress;setProgress:(f:any)=>void}){const selected=buildAdaptiveReviewDeck(progress,exercises,10),weak=Object.values(progress.mastery||{}).filter(m=>m.attempts>=2&&m.score<.58).sort((a,b)=>a.score-b.score).slice(0,3);return <div className="space-y-5"><div className="card"><div className="text-sm font-bold text-lime-700">Adaptive Wiederholung</div><h2 className="mt-1 text-3xl font-black">Nicht einfach alles nochmal</h2><p className="mt-2 text-slate-600">Die Auswahl kombiniert Fälligkeit, Fehler, Mastery, Antworttempo und verzögerten Grammatik-Transfer.</p>{weak.length>0&&<div className="mt-4 flex flex-wrap gap-2">{weak.map(w=><span key={w.key} className="rounded-full bg-amber-50 px-3 py-2 text-sm font-semibold">{w.key.replace(/^(vocab|grammar|skill):/,'')} · {Math.round(w.score*100)}%</span>)}</div>}</div><ExerciseDeck exercises={selected} onResult={(e,c,m)=>handleExercise(e,c,m,setProgress)}/></div>}
function SpeakView({setProgress}:{setProgress:(f:any)=>void}){const [idx,setIdx]=useState(0),prompts=[['Kje si zdaj?','Zdaj sem v Sloveniji.'],['Od kod si?','Sem iz Nemčije.'],['Kje živiš?','Živim v Nemčiji.'],['Kaj piješ?','Pijem vodo.'],['Kdaj greš spat?','Grem spat ob desetih.']];return <div className="space-y-5"><div className="card"><h2 className="text-3xl font-black">Sprechen</h2><p className="mt-2 text-slate-600">Hören → selbst antworten → korrigieren.</p></div><SpeechPractice prompt={prompts[idx][0]} expected={prompts[idx][1]} onResult={correct=>{setProgress((p:UserProgress)=>({...p,speakingMinutes:+(p.speakingMinutes+.2).toFixed(1)}));if(correct)setTimeout(()=>setIdx((idx+1)%prompts.length),900)}}/><TutorChat/></div>}
function VocabView({progress}:{progress:UserProgress}){const [q,setQ]=useState(''),[category,setCategory]=useState('Alle'),cats=['Alle',...Array.from(new Set(vocabulary.map(v=>v.category)))],list=useMemo(()=>vocabulary.filter(v=>(category==='Alle'||v.category===category)&&(`${v.sl} ${v.de}`.toLowerCase().includes(q.toLowerCase()))),[q,category]);return <div className="space-y-4"><div className="card"><h2 className="text-3xl font-black">Vokabeln</h2><p className="mt-2 text-slate-600">{vocabulary.length} Wörter im aktuellen Testbestand.</p><div className="mt-4 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 text-slate-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-2xl border border-slate-200 py-3 pl-10 pr-3" placeholder="Slowenisch oder Deutsch …"/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="max-w-36 rounded-2xl border border-slate-200 px-3">{cats.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="grid gap-3 lg:grid-cols-2">{list.map(x=><div key={x.id} className="card flex gap-3"><AudioButton text={x.sl} compact/><div className="flex-1"><div className="flex justify-between gap-2"><b className="text-lg">{x.sl}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{progress.secureWords.includes(x.id)?'sicher':progress.wordsLearned.includes(x.id)?'gelernt':progress.introducedWords.includes(x.id)?'eingeführt':'neu'}</span></div><div className="text-slate-600">{x.de}</div><div className="mt-2 text-sm"><b>{x.example}</b><div className="text-slate-500">{x.exampleDe}</div></div></div></div>)}</div></div>}
function ProgressView({progress,cloud,syncState}:{progress:UserProgress;cloud:boolean;syncState:string}){const top=[...progress.mistakes].sort((a,b)=>b.count-a.count).slice(0,5),weak=Object.values(progress.mastery||{}).filter(m=>m.attempts>=2).sort((a,b)=>a.score-b.score).slice(0,5),recent=progress.recentAttempts||[],avg=recent.length?Math.round(recent.slice(-20).reduce((s,a)=>s+a.responseMs,0)/Math.min(20,recent.length)/1000):0;return <div className="space-y-5"><div className="card"><h2 className="text-3xl font-black">Fortschritt</h2><p className="mt-2 text-slate-600">{cloud?`Cloud-Sync: ${syncState}. Lokale Offline-Kopie bleibt erhalten.`:'Dein Fortschritt ist lokal gespeichert. Über „Konto“ kannst du Geräte-Synchronisation aktivieren.'}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Brain} value={`${progress.wordsLearned.length}`} label="gelernte Wörter"/><Metric icon={Trophy} value={`${progress.secureWords.length}`} label="sichere Wörter"/><Metric icon={Mic2} value={`${progress.speakingMinutes.toFixed(1)} min`} label="Sprechzeit"/><Metric icon={Headphones} value={avg?`${avg} s`:'–'} label="Ø Antwortzeit"/></div><div className="grid gap-4 lg:grid-cols-2"><div className="card"><h3 className="text-xl font-black">Häufigste Fehler</h3>{top.length?<div className="mt-4 space-y-2">{top.map(m=><div key={m.key} className="flex justify-between rounded-2xl bg-amber-50 p-3"><span>{exercises.find(e=>e.id===m.key)?.prompt??m.key}</span><b>{m.count}×</b></div>)}</div>:<p className="mt-3 text-slate-500">Noch keine Fehler gespeichert.</p>}</div><div className="card"><h3 className="text-xl font-black">Adaptive Schwerpunkte</h3>{weak.length?<div className="mt-4 space-y-2">{weak.map(m=><div key={m.key} className="flex justify-between rounded-2xl bg-lime-50 p-3"><span>{m.key.replace(/^(vocab|grammar|skill):/,'')}</span><b>{Math.round(m.score*100)} %</b></div>)}</div>:<p className="mt-3 text-slate-500">Nach einigen Übungen erkennt die App hier deine schwächeren Bereiche.</p>}</div></div></div>}
function handleExercise(ex:Exercise,correct:boolean,meta:ExerciseResultMeta,setProgress:(f:any)=>void){setProgress((p:UserProgress)=>{const attemptCount=(p.recentAttempts?.length||0)+1;return {...p,reviews:scheduleReview(p.reviews,ex.id,correct),mistakes:correct?p.mistakes:registerMistake(p.mistakes,ex.id),mastery:updateMastery(p.mastery||{},ex,correct,meta.responseMs,meta.hintsUsed),recentAttempts:recordAttempt(p.recentAttempts||[],{exerciseId:ex.id,correct,responseMs:meta.responseMs,hintsUsed:meta.hintsUsed,occurredAt:Date.now()}),transferQueue:queueTransfers(p.transferQueue||[],ex,correct,attemptCount)}})}
