'use client'

import { useState } from 'react'
import { CloudSession, cloudConfigured, ensureProfile, saveCloudProgress, signIn, signOut, signUp } from '@/lib/cloud-sync'
import { defaultPreferences, loadProgress, resetLearningProgress, saveProgress } from '@/lib/storage'
import { LearnerPreferences } from '@/types'

export default function AccountMenu({session,syncState,preferences=defaultPreferences,onSession,onPreferences}:{session:CloudSession|null;syncState:string;preferences?:LearnerPreferences;onSession:(s:CloudSession|null)=>void;onPreferences?:(p:LearnerPreferences)=>void}){
  const [open,setOpen]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmReset,setConfirmReset]=useState(false)
  async function login(create=false){setBusy(true);setMessage('');try{const s=create?await signUp(email,password):await signIn(email,password);if(s){onSession(s);setMessage('Angemeldet – Fortschritt wird synchronisiert.')}else setMessage('Bitte bestätige deine E-Mail und melde dich danach an.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
  async function logout(){await signOut();onSession(null);setOpen(false)}
  async function resetLearning(){setBusy(true);setMessage('');try{const owner=session?.user.id||null,current=loadProgress(owner),fresh=resetLearningProgress(current);saveProgress(fresh,owner);if(session){const profile=await ensureProfile(session);await saveCloudProgress(session,profile.id,fresh)}setMessage('Lernstand wurde zurückgesetzt.');setConfirmReset(false);setTimeout(()=>window.location.reload(),350)}catch(e:any){setMessage(e?.message||'Lernstand konnte nicht vollständig zurückgesetzt werden.');setBusy(false)}}
  function change(next:LearnerPreferences){onPreferences?.(next)}
  const label=session?.user?.email?.split('@')[0]||'Konto'
  return <div className="relative"><button onClick={()=>setOpen(!open)} className="rounded-full bg-white px-3 py-2 text-sm font-bold shadow-soft">{label}</button>{open&&<div className="absolute right-0 top-12 z-[70] max-h-[75vh] w-[min(22rem,calc(100vw-2rem))] overflow-y-auto rounded-3xl bg-white p-4 shadow-2xl ring-1 ring-slate-100">
    {session?<><div className="font-black">{session.user.email||'Benutzerkonto'}</div><div className="mt-1 text-sm text-slate-500">Sync: {syncState}</div><div className="mt-4 rounded-2xl bg-lime-50 p-3 text-sm">Dein Lernstand wird zusätzlich lokal gespeichert. Offline kannst du weiterlernen.</div></>:<><div className="font-black">Lernstand synchronisieren</div><p className="mt-1 text-sm text-slate-500">Mit einem Konto kannst du auf mehreren Geräten weitermachen.</p>{!cloudConfigured()&&<div className="mt-3 rounded-2xl bg-amber-50 p-3 text-sm">Cloud-Synchronisation ist derzeit nicht verfügbar.</div>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-Mail" className="mt-4 w-full rounded-2xl border border-slate-200 px-4 py-3"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Passwort" className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3"/>{message&&<div className="mt-3 text-sm text-slate-600">{message}</div>}<button disabled={busy||!email||password.length<6} onClick={()=>login(false)} className="btn-primary mt-4 w-full justify-center disabled:opacity-40">Anmelden</button><button disabled={busy||!email||password.length<6} onClick={()=>login(true)} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 font-bold disabled:opacity-40">Konto erstellen</button></>}
    <div className="my-4 border-t border-slate-100"/><div className="font-black">Lerneinstellungen</div><label className="mt-3 block text-xs font-bold uppercase tracking-wide text-slate-400">Tagesziel</label><select disabled={!onPreferences} value={preferences.dailyGoalMinutes} onChange={e=>change({...preferences,dailyGoalMinutes:Number(e.target.value) as LearnerPreferences['dailyGoalMinutes']})} className="mt-1 w-full rounded-2xl border border-slate-200 px-3 py-3 disabled:opacity-50"><option value={5}>5 Minuten</option><option value={10}>10 Minuten</option><option value={15}>15 Minuten</option><option value={20}>20 Minuten</option><option value={30}>30 Minuten</option></select><label className="mt-3 block text-xs font-bold uppercase tracking-wide text-slate-400">Tempo</label><select disabled={!onPreferences} value={preferences.pace} onChange={e=>change({...preferences,pace:e.target.value as LearnerPreferences['pace']})} className="mt-1 w-full rounded-2xl border border-slate-200 px-3 py-3 disabled:opacity-50"><option value="ruhig">Ruhig</option><option value="normal">Normal</option><option value="intensiv">Intensiv</option></select><label className="mt-3 block text-xs font-bold uppercase tracking-wide text-slate-400">Audio</label><select disabled={!onPreferences} value={preferences.audioSpeed} onChange={e=>change({...preferences,audioSpeed:e.target.value as LearnerPreferences['audioSpeed']})} className="mt-1 w-full rounded-2xl border border-slate-200 px-3 py-3 disabled:opacity-50"><option value="langsam">Langsam</option><option value="normal">Normal</option></select>
    <div className="my-4 border-t border-slate-100"/><div className="font-black">Lernstand</div>{confirmReset?<div className="mt-3 rounded-2xl bg-red-50 p-3"><div className="font-bold">Lernstand wirklich zurücksetzen?</div><p className="mt-1 text-sm text-slate-600">Lektionen, Wiederholungen, Fehler, Mastery und eingeführte Inhalte werden gelöscht. Dein Konto und deine Lerneinstellungen bleiben bestehen.</p><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>setConfirmReset(false)} className="rounded-xl border border-slate-200 px-3 py-2 font-bold">Abbrechen</button><button disabled={busy} onClick={resetLearning} className="rounded-xl bg-red-600 px-3 py-2 font-bold text-white">Zurücksetzen</button></div></div>:<button onClick={()=>setConfirmReset(true)} className="mt-3 w-full rounded-2xl border border-red-200 px-4 py-3 font-bold text-red-700">Lernstand zurücksetzen</button>}{message&&session&&<div className="mt-3 text-sm text-slate-600">{message}</div>}{session&&<button onClick={logout} className="mt-4 w-full rounded-2xl border border-slate-200 px-4 py-3 font-bold">Abmelden</button>}
  </div>}</div>
}
