'use client'

import { useEffect,useMemo,useRef,useState } from 'react'
import { evaluateAnswer,EvaluationResult } from '@/lib/answer-evaluation'
import { Exercise } from '@/types'
import { stableChoiceOptions } from '@/lib/exercise-integrity'

export type ExerciseResultMeta={responseMs:number;hintsUsed:number}
type ResultRow={correct:boolean;responseMs:number;vocabularyIds:string[];grammarRuleIds:string[]}

export default function ExerciseDeck({exercises,onResult,onComplete}:{exercises:Exercise[];onResult:(e:Exercise,c:boolean,meta:ExerciseResultMeta)=>void;onComplete?:()=>void}){
 const [i,setI]=useState(0),[value,setValue]=useState(''),[checked,setChecked]=useState(false),[finished,setFinished]=useState(false),[showHint,setShowHint]=useState(false),[evaluation,setEvaluation]=useState<EvaluationResult|null>(null),[results,setResults]=useState<ResultRow[]>([])
 const startedAt=useRef(Date.now()),sessionSeed=useRef(`${Date.now()}-${Math.random()}`),ex=exercises[i]
 useEffect(()=>{startedAt.current=Date.now();setValue('');setChecked(false);setShowHint(false);setEvaluation(null)},[ex?.id])
 const choiceOptions=useMemo(()=>!ex||ex.type!=='choice'?[]:stableChoiceOptions(ex,sessionSeed.current),[ex?.id])
 if(!exercises.length)return <div className="card">Für diesen Lernblock sind noch keine Übungen vorhanden.</div>
 if(finished){const correctCount=results.filter(r=>r.correct).length,errorCount=results.length-correctCount,avg=results.length?Math.round(results.reduce((s,r)=>s+r.responseMs,0)/results.length/1000):0,words=new Set(results.filter(r=>r.correct).flatMap(r=>r.vocabularyIds)).size,grammarErrors=new Set(results.filter(r=>!r.correct).flatMap(r=>r.grammarRuleIds)).size;return <div className="card"><div className="text-sm font-bold text-lime-700">Heute geschafft</div><h3 className="mt-2 text-2xl font-black">Lernblock abgeschlossen</h3><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-lime-50 p-3"><b className="text-xl">{results.length}</b><div className="text-xs text-slate-500">Aufgaben</div></div><div className="rounded-2xl bg-lime-50 p-3"><b className="text-xl">{correctCount}</b><div className="text-xs text-slate-500">richtig</div></div><div className="rounded-2xl bg-amber-50 p-3"><b className="text-xl">{errorCount}</b><div className="text-xs text-slate-500">Fehler</div></div><div className="rounded-2xl bg-slate-50 p-3"><b className="text-xl">{avg||'–'}{avg?' s':''}</b><div className="text-xs text-slate-500">Ø Antwort</div></div></div><p className="mt-4 text-sm text-slate-600">{words} Wörter aktiv geübt{grammarErrors?` · ${grammarErrors} Grammatikbereich${grammarErrors===1?'':'e'} bleiben im Fokus.`:'.'}</p><button onClick={onComplete} className="btn-primary mt-5 justify-center">Weiter</button></div>}
 function evaluate(answer:string){if(ex.type==='choice'){const selected=choiceOptions.find(o=>o.text===answer);const ok=Boolean(selected?.correct);return {classification:ok?'CORRECT':'WRONG_MEANING',isCorrect:ok,normalizedInput:answer,normalizedExpected:ex.answer,issues:[],explanation:ok?undefined:`Richtig ist: ${ex.answer}`} as EvaluationResult}return evaluateAnswer({input:answer,expected:ex.answer,alternatives:ex.acceptedAnswers})}
 function submit(answer=value){if(!ex||!answer.trim()||checked)return;const currentExercise=ex;const result=evaluate(answer),responseMs=Math.max(250,Date.now()-startedAt.current),hintsUsed=showHint?1:0;setValue(answer);setEvaluation(result);setChecked(true);setResults(r=>[...r,{correct:result.isCorrect,responseMs,vocabularyIds:currentExercise.vocabularyIds||[],grammarRuleIds:currentExercise.grammarRuleIds||[]}]);onResult(currentExercise,result.isCorrect,{responseMs,hintsUsed})}
 function next(){if(i>=exercises.length-1){setFinished(true);return}setI(v=>v+1)}
 const correct=evaluation?.isCorrect??false,classificationLabel=evaluation?.classification==='ACCEPTABLE_VARIANT'?'Auch richtig':evaluation?.classification==='MINOR_TYPO'?'Fast richtig':evaluation?.classification==='GRAMMAR_ERROR'?'Grammatik':evaluation?.classification==='INCOMPLETE'?'Noch unvollständig':null
 return <div className="card"><div className="mb-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-lime-400 transition-all" style={{width:`${Math.round(((i+(checked?1:0))/exercises.length)*100)}%`}}/></div><div className="text-sm font-bold text-lime-700">Aufgabe {i+1} von {exercises.length}</div><h3 className="mt-2 text-xl font-black">{ex.prompt}</h3>{ex.hint&&!checked&&<button type="button" onClick={()=>setShowHint(true)} className="mt-2 text-sm font-semibold text-slate-500 underline">{showHint?`Hinweis: ${ex.hint}`:'Hinweis anzeigen'}</button>}{ex.type==='choice'?<div className="mt-5 grid gap-2">{choiceOptions.map((option,index)=><button key={option.id} disabled={checked} onClick={()=>submit(option.text)} className={`rounded-2xl border px-4 py-3 text-left font-semibold transition ${checked&&option.correct?'border-lime-500 bg-lime-50':checked&&value===option.text?'border-amber-400 bg-amber-50':'border-slate-200 bg-white hover:border-lime-400'}`}><span className="mr-3 text-slate-400">{String.fromCharCode(65+index)}</span>{option.text}</button>)}</div>:<><input value={value} disabled={checked} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit()}} className="mt-5 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-lime-500" placeholder="Deine Antwort …"/><div className="mt-2 flex gap-2">{['č','š','ž'].map(ch=><button key={ch} type="button" disabled={checked} onClick={()=>setValue(v=>v+ch)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 font-black">{ch.toUpperCase()}</button>)}</div><button onClick={()=>submit()} disabled={!value.trim()||checked} className="btn-primary mt-3 w-full justify-center">Prüfen</button></>}{checked&&<div className={`mt-4 rounded-2xl p-4 ${correct?'bg-lime-50':'bg-amber-50'}`}>{correct?<><b>{evaluation?.classification==='ACCEPTABLE_VARIANT'?'Auch richtig!':'Pravilno!'}</b> {evaluation?.classification==='ACCEPTABLE_VARIANT'?'Diese Formulierung ist ebenfalls korrekt.':'Genau richtig.'}</>:<><b>{classificationLabel??'Noch nicht.'}</b><div className="mt-1">{evaluation?.explanation??`Richtig: ${ex.answer}`}</div>{ex.explanation&&evaluation?.classification!=='GRAMMAR_ERROR'&&<div className="mt-2 text-sm">Warum? {ex.explanation}</div>}</>}<button onClick={next} className="mt-3 font-bold underline">{i===exercises.length-1?'Block abschließen':'Nächste Aufgabe'}</button></div>}</div>
}
