'use client'

import { useMemo,useState } from 'react'
import { ChevronRight } from 'lucide-react'
import AudioButton from '@/components/AudioButton'
import ExerciseDeck,{ExerciseResultMeta} from '@/components/ExerciseDeck'
import { exercises,lessons,vocabulary } from '@/data/seed'
import { grammarDefinitions,grammarPrerequisitesMet } from '@/lib/curriculum-access'
import { buildLearningBlocks,lessonProgress } from '@/lib/learning-flow'
import { buildExamPlan,examSize } from '@/lib/exam-planner'
import { allVerbFormsReady,buildVerbPracticeExercises,verbIntrosForVocabulary } from '@/lib/verb-learning'
import { Exercise,UserProgress,VerbFormRequirement } from '@/types'

type Stage='intro'|'learn'|'verb-intro'|'verb-practice'|'grammar-intro'|'practice'|'final'|'done'
function blockSize(progress:UserProgress){return progress.preferences.pace==='ruhig'?2:3}
export default function LessonFlow({lessonId,progress,setProgress,onExerciseResult,onFinish}:{lessonId:number;progress:UserProgress;setProgress:(f:any)=>void;onExerciseResult:(e:Exercise,c:boolean,meta:ExerciseResultMeta)=>void;onFinish:()=>void}){
 const lesson=lessons.find(l=>l.id===lessonId)!,[examSeed]=useState(()=>Date.now()),[blocks]=useState(()=>buildLearningBlocks(lessonId,vocabulary,exercises,progress.introducedWords,blockSize(progress))),[stage,setStage]=useState<Stage>(blocks.length?'intro':'final'),[blockIndex,setBlockIndex]=useState(0),[wordIndex,setWordIndex]=useState(0),[verbIndex,setVerbIndex]=useState(0),[verbRound,setVerbRound]=useState(0),block=blocks[blockIndex],percent=stage==='done'?100:blocks.length?lessonProgress(blockIndex,blocks.length,stage==='practice'?1:0,2):75
 const blockRuleIds=useMemo(()=>Array.from(new Set((block?.exercises||[]).flatMap(e=>e.grammarRuleIds||[]))),[block]),pendingRules=blockRuleIds.filter(id=>!progress.introducedGrammarRules.includes(id)&&grammarPrerequisitesMet(id,progress,blockRuleIds)),ruleCards=grammarDefinitions(pendingRules),verbIntros=verbIntrosForVocabulary(block?.words.map(w=>w.id)||[]),currentVerb=verbIntros[verbIndex]
 const verbPractice=currentVerb?buildVerbPracticeExercises(lessonId,currentVerb):[]
 const practice=useMemo(()=>block?buildExamPlan({kind:'checkpoint',lessonId,exercises:block.exercises,vocabulary,progress,seed:examSeed+blockIndex*101,targetSize:examSize('checkpoint',progress,block.words.length)}):[],[block,blockIndex,examSeed,lessonId,progress])
 const finalReview=useMemo(()=>buildExamPlan({kind:'final',lessonId,exercises,vocabulary,progress,seed:examSeed+9001,targetSize:examSize('final',progress)}),[examSeed,lessonId,progress])
 function markWord(id:string){setProgress((p:UserProgress)=>({...p,introducedWords:Array.from(new Set([...p.introducedWords,id])),updatedAt:Date.now()}))}
 function afterWords(){setWordIndex(0);setVerbIndex(0);if(verbIntros.length)setStage('verb-intro');else if(pendingRules.length)setStage('grammar-intro');else setStage('practice')}
 function nextWord(){if(!block)return;markWord(block.words[wordIndex].id);if(wordIndex<block.words.length-1)setWordIndex(wordIndex+1);else afterWords()}
 function unlockCurrentVerb(){if(!currentVerb)return;setProgress((p:UserProgress)=>({...p,introducedVerbForms:Array.from(new Set([...p.introducedVerbForms,...currentVerb.keys])),introducedGrammarRules:Array.from(new Set([...p.introducedGrammarRules,'verb-first-person'])),updatedAt:Date.now()}));setVerbRound(v=>v+1);setStage('verb-practice')}
 function currentRequirements():VerbFormRequirement[]{return currentVerb?.forms.map(f=>({verbId:currentVerb.verbId,person:f.person,number:'singular'}))||[]}
 function finishVerbPractice(){if(!currentVerb)return;if(!allVerbFormsReady(progress,currentRequirements())){setVerbRound(v=>v+1);return}if(verbIndex<verbIntros.length-1){setVerbIndex(v=>v+1);setStage('verb-intro')}else if(pendingRules.filter(r=>r!=='verb-first-person').length)setStage('grammar-intro');else setStage('practice')}
 function unlockGrammar(){setProgress((p:UserProgress)=>({...p,introducedGrammarRules:Array.from(new Set([...p.introducedGrammarRules,...pendingRules])),updatedAt:Date.now()}));setStage('practice')}
 function nextBlock(){if(blockIndex<blocks.length-1){setBlockIndex(blockIndex+1);setWordIndex(0);setVerbIndex(0);setStage('learn')}else setStage('final')}
 if(!lesson)return null
 return <div className="w-full max-w-full space-y-5 overflow-x-hidden"><div className="card"><div className="flex items-center justify-between gap-3"><div className="text-sm font-bold text-lime-700">Lektion {lesson.id}</div><div className="text-sm font-bold text-slate-500">{percent}%</div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-lime-400 transition-all" style={{width:`${percent}%`}}/></div><h2 className="mt-4 break-words text-3xl font-black">{lesson.title}</h2><p className="mt-2 text-slate-600">{lesson.subtitle}</p></div>
 {stage==='intro'&&<div className="card"><h3 className="text-xl font-black">Heute lernst du in kleinen Portionen</h3><p className="mt-2 text-slate-600">Neue Wörter, Verben und Grammatik werden zuerst vollständig vorgestellt. Erst danach werden sie in normalen Sätzen abgefragt.</p><button onClick={()=>setStage('learn')} className="btn-primary mt-5">Los geht’s <ChevronRight size={18}/></button></div>}
 {stage==='learn'&&block&&<div className="card overflow-hidden"><div className="text-sm font-bold text-lime-700">Lernblock {blockIndex+1} von {blocks.length} · Wort {wordIndex+1} von {block.words.length}</div><div className="mt-5 grid min-w-0 grid-cols-1 gap-4 lg:grid-cols-2"><div className="min-w-0"><AudioButton text={block.words[wordIndex].sl}/></div><div className="min-w-0"><div className="break-words text-3xl font-black">{block.words[wordIndex].sl}</div><div className="mt-1 text-lg text-slate-600">{block.words[wordIndex].de}</div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><b>{block.words[wordIndex].example}</b><div className="mt-1 text-sm text-slate-500">{block.words[wordIndex].exampleDe}</div></div></div></div><button onClick={nextWord} className="btn-primary mt-5 w-full justify-center">{wordIndex===block.words.length-1?'Weiter':'Nächstes Wort'} <ChevronRight size={18}/></button></div>}
 {stage==='verb-intro'&&currentVerb&&<div className="card"><div className="text-sm font-bold text-blue-700">Neues Verb · {verbIndex+1} von {verbIntros.length}</div><div className="mt-2 flex flex-wrap items-center gap-3"><h3 className="text-3xl font-black">{currentVerb.infinitiveSl} – {currentVerb.infinitiveDe}</h3><AudioButton text={currentVerb.infinitiveSl} compact/></div><p className="mt-2 text-slate-600">Dieses Verb lernst du zuerst vollständig im Singular. Dual und Plural kommen später als eigene Lernstufen.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{currentVerb.forms.map(f=><div key={f.person} className="rounded-2xl bg-blue-50 p-4"><div className="flex items-center justify-between gap-2"><b className="text-lg">{f.pronounSl} {f.formSl}</b><AudioButton text={`${f.pronounSl.split(' / ')[0]} ${f.formSl}`} compact/></div><div className="mt-1 text-sm text-slate-600">{f.translationDe}</div></div>)}</div>{currentVerb.examples.length>0&&<div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="font-black">Beispiele</div><div className="mt-2 space-y-2">{currentVerb.examples.map(x=><div key={x.sl}><b>{x.sl}</b><div className="text-sm text-slate-500">{x.de}</div></div>)}</div></div>}<button onClick={unlockCurrentVerb} className="btn-primary mt-5 w-full justify-center">Konjugation üben <ChevronRight size={18}/></button></div>}
 {stage==='verb-practice'&&currentVerb&&<><div className="card"><div className="text-sm font-bold text-blue-700">Konjugationstraining · {currentVerb.infinitiveSl}</div><h3 className="mt-1 text-2xl font-black">Erst sicher anwenden, dann in Sätzen benutzen</h3><p className="mt-2 text-slate-600">Jede Singularform wird erkannt und aktiv produziert. Bei Fehlern folgt eine weitere Runde, bevor das Verb für normale Aufgaben freigegeben wird.</p></div><ExerciseDeck key={`${currentVerb.verbId}-${verbRound}`} exercises={verbPractice} onResult={onExerciseResult} onComplete={finishVerbPractice}/></>}
 {stage==='grammar-intro'&&<div className="card"><div className="text-sm font-bold text-lime-700">Erst verstehen, dann üben</div><h3 className="mt-1 text-2xl font-black">Neue Grammatik in diesem Lernblock</h3>{ruleCards.filter(r=>r.id!=='verb-first-person').map(r=><div key={r.id} className="mt-4 rounded-2xl bg-lime-50 p-4"><div className="font-black">{r.title}</div><p className="mt-1 text-sm text-slate-600">{r.body}</p><div className="mt-2 space-y-1 text-sm font-semibold">{r.examples.map(x=><div key={x}>{x}</div>)}</div></div>)}<button onClick={unlockGrammar} className="btn-primary mt-5 w-full justify-center">Jetzt üben <ChevronRight size={18}/></button></div>}
 {stage==='practice'&&block&&(practice.length?<><div className="card"><div className="text-sm font-bold text-lime-700">Zwischenprüfung · {practice.length} Aufgaben</div><p className="mt-1 text-sm text-slate-600">Hier erscheinen nur Wörter, Grammatik und Verbformen, die bereits ausreichend trainiert wurden.</p></div><ExerciseDeck exercises={practice} onResult={onExerciseResult} onComplete={nextBlock}/></>:<div className="card"><h3 className="text-xl font-black">Dieser Block ist vorbereitet</h3><p className="mt-2 text-slate-600">Noch keine passende normale Übung ist freigeschaltet. Wir gehen weiter, statt unsichere oder unbekannte Formen abzufragen.</p><button onClick={nextBlock} className="btn-primary mt-4">Weiter</button></div>)}
 {stage==='final'&&<><div className="card"><div className="text-sm font-bold text-lime-700">Abschlussprüfung · {finalReview.length} Aufgaben</div><h3 className="mt-1 text-2xl font-black">Breiter Test über die ganze Lektion</h3><p className="mt-2 text-slate-600">Nur bereits eingeführte und ausreichend trainierte Inhalte werden geprüft.</p></div>{finalReview.length?<ExerciseDeck exercises={finalReview} onResult={onExerciseResult} onComplete={()=>setStage('done')}/>:<button onClick={()=>setStage('done')} className="btn-primary">Lektion abschließen</button>}</>}
 {stage==='done'&&<div className="card text-center"><div className="text-sm font-bold text-lime-700">100 %</div><h3 className="mt-2 text-3xl font-black">Lektion geschafft</h3><p className="mt-2 text-slate-600">Einzelne Wörter oder Regeln können trotzdem noch im Status „lernen“ sein.</p><button onClick={onFinish} className="btn-primary mt-5 justify-center">Lektion abschließen</button></div>}</div>
}
