'use client'

import { useEffect,useRef,useState } from 'react'
import { Send,Sparkles,Lightbulb,RotateCcw,CheckCircle2 } from 'lucide-react'
import AudioButton from './AudioButton'
import { CONVERSATION_CURRICULUM,dialogueProgress,type ConversationTopic } from '@/lib/conversation-curriculum'

type Progress={current:number;total:number;percent:number}
type Msg={role:'user'|'tutor';text:string;translation?:string;hint?:string;status?:string;adaptation?:string}

export default function TutorChat(){
 const initial=CONVERSATION_CURRICULUM[0]
 const [topic,setTopic]=useState<ConversationTopic>(initial.id)
 const [messages,setMessages]=useState<Msg[]>([{role:'tutor',text:initial.steps[0].prompt,translation:initial.steps[0].translation,hint:initial.steps[0].hint}])
 const [input,setInput]=useState('');const[busy,setBusy]=useState(false);const[showTranslations,setShowTranslations]=useState(true);const[hintLevel,setHintLevel]=useState(0);const[progress,setProgress]=useState<Progress>(dialogueProgress(initial.id,initial.steps[0].id));const[completed,setCompleted]=useState(false);const scrollRef=useRef<HTMLDivElement|null>(null)
 useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:'smooth'})},[messages])
 const scenario=CONVERSATION_CURRICULUM.find(s=>s.id===topic)??initial
 function chooseTopic(id:ConversationTopic){const s=CONVERSATION_CURRICULUM.find(x=>x.id===id)??initial;setTopic(id);setMessages([{role:'tutor',text:s.steps[0].prompt,translation:s.steps[0].translation,hint:s.steps[0].hint}]);setHintLevel(0);setInput('');setCompleted(false);setProgress(dialogueProgress(id,s.steps[0].id))}
 async function send(forced?:string){const text=(forced??input).trim();if(!text||busy||completed)return;const next=[...messages,{role:'user' as const,text}];setMessages(next);setInput('');setBusy(true);try{const r=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:next.slice(-14),context:{topic,hintLevel}})});const data=await r.json();setMessages(m=>[...m,{role:'tutor',text:data.reply||'Poskusi še enkrat.',translation:data.translation,hint:data.hint,status:data.status,adaptation:data.adaptation}]);if(data.progress)setProgress(data.progress);setCompleted(Boolean(data.completed));setHintLevel(data.adaptation==='reinforce'?Math.min(4,hintLevel+1):0)}catch{setMessages(m=>[...m,{role:'tutor',text:'Poskusi še enkrat.'}])}finally{setBusy(false)}}
 const lastTutor=[...messages].reverse().find(m=>m.role==='tutor')
 return <div className="card min-w-0">
  <div className="mb-3 flex items-center gap-2"><Sparkles size={20}/><div className="min-w-0"><h3 className="text-xl font-black">Adaptiver Dialog</h3><div className="text-xs text-slate-500 dark:text-slate-400">{scenario.goal}</div></div><span className="ml-auto rounded-full bg-lime-100 px-2 py-1 text-xs font-bold text-slate-900">{scenario.level}</span></div>
  <div className="mb-3"><div className="mb-1 flex items-center justify-between text-xs font-semibold text-slate-500 dark:text-slate-400"><span>Gesprächsfortschritt</span><span>{progress.current}/{progress.total}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full bg-lime-400 transition-all" style={{width:`${progress.percent}%`}}/></div></div>
  <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{CONVERSATION_CURRICULUM.map(t=><button key={t.id} onClick={()=>chooseTopic(t.id)} className={`shrink-0 rounded-full px-3 py-2 text-sm font-semibold ${topic===t.id?'bg-slate-950 text-white dark:bg-lime-300 dark:text-slate-950':'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200'}`}>{t.label}</button>)}</div>
  <div className="mb-3 flex flex-wrap gap-1.5">{scenario.grammarTargets.map(t=><span key={t} className="rounded-full bg-slate-50 px-2 py-1 text-[11px] text-slate-500 dark:bg-slate-900 dark:text-slate-400">{t}</span>)}</div>
  <div ref={scrollRef} className="max-h-80 space-y-3 overflow-y-auto pr-1 sm:max-h-96">{messages.map((m,i)=><div key={i} className={`rounded-2xl p-3 ${m.role==='user'?'ml-6 bg-lime-100 text-slate-950 sm:ml-10':m.status==='correction'?'mr-6 bg-amber-50 text-slate-950 sm:mr-10 dark:bg-amber-950 dark:text-amber-100':m.status==='off-topic'?'mr-6 bg-rose-50 text-slate-950 sm:mr-10 dark:bg-rose-950 dark:text-rose-100':'mr-6 bg-slate-100 text-slate-950 sm:mr-10 dark:bg-slate-800 dark:text-slate-100'}`}><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><div className="break-words">{m.text}</div>{showTranslations&&m.translation&&<div className="mt-1 text-sm text-slate-500 dark:text-slate-400">{m.translation}</div>}{m.hint&&<div className="mt-2 rounded-xl bg-white/70 px-3 py-2 text-sm dark:bg-slate-900/70"><strong>Tipp:</strong> {m.hint}</div>}{m.adaptation==='reinforce'&&<div className="mt-2 text-xs font-semibold text-amber-700 dark:text-amber-300">Dieser Schritt wird noch einmal gefestigt.</div>}</div>{m.role==='tutor'&&<AudioButton text={m.text.split(/(?<=[.!?])\s/)[0]} compact/>}</div></div>)}</div>
  {completed&&<div className="mt-3 flex items-center gap-2 rounded-2xl bg-lime-50 p-3 text-sm font-semibold text-lime-800 dark:bg-lime-950 dark:text-lime-200"><CheckCircle2 size={18}/>Gesprächsziel erreicht. Du kannst das Szenario neu starten oder ein anderes wählen.</div>}
  <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setShowTranslations(v=>!v)} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold dark:bg-slate-800">{showTranslations?'Übersetzung aus':'Übersetzung an'}</button><button disabled={completed} onClick={()=>{setHintLevel(v=>Math.min(4,v+1));void send('Ne razumem')}} className="flex items-center gap-1 rounded-full bg-amber-100 px-3 py-2 text-xs font-semibold text-slate-900 disabled:opacity-40"><Lightbulb size={14}/> Hilfe</button>{lastTutor?.hint&&!completed&&<button onClick={()=>setInput(lastTutor.hint||'')} className="rounded-full bg-lime-100 px-3 py-2 text-xs font-semibold text-slate-900">Tipp übernehmen</button>}<button onClick={()=>chooseTopic(topic)} className="flex items-center gap-1 rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold dark:bg-slate-800"><RotateCcw size={14}/> Neu starten</button></div>
  <div className="mt-4 flex gap-2"><input value={input} disabled={completed} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} className="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-900" placeholder={completed?'Gespräch abgeschlossen':'Antworte auf Slowenisch …'}/><button onClick={()=>void send()} disabled={busy||completed||!input.trim()} className="btn-primary px-4" aria-label="Antwort senden"><Send size={18}/></button></div>
 </div>
}
