export type A1SkillDomain='communication'|'vocabulary'|'grammar'|'listening'|'speaking'|'reading'
export type A1Skill={id:string;title:string;domain:A1SkillDomain;prerequisites:string[];outcomes:string[];grammarTargets?:string[];vocabularyTopics?:string[]}

export const A1_SKILL_GRAPH:A1Skill[]=[
{id:'a1-greetings',title:'Begrüßen und verabschieden',domain:'communication',prerequisites:[],outcomes:['einfache Begrüßungen verstehen und verwenden','sich verabschieden'],vocabularyTopics:['Begrüßung','Höflichkeit']},
{id:'a1-introduce-self',title:'Sich vorstellen',domain:'speaking',prerequisites:['a1-greetings'],outcomes:['Name, Herkunft und einfache persönliche Angaben nennen','nach Name und Herkunft fragen'],grammarTargets:['biti-present','personal-pronouns'],vocabularyTopics:['Person','Länder']},
{id:'a1-numbers-time',title:'Zahlen, Uhrzeit und Tageszeiten',domain:'vocabulary',prerequisites:['a1-greetings'],outcomes:['Grundzahlen verstehen','einfache Uhrzeiten und Tageszeiten ausdrücken'],vocabularyTopics:['Zahlen','Zeit']},
{id:'a1-family',title:'Familie und Personen',domain:'communication',prerequisites:['a1-introduce-self','a1-numbers-time'],outcomes:['enge Familienmitglieder benennen','einfache Beziehungen beschreiben'],grammarTargets:['gender-basic','dual-introduction','imeti-present'],vocabularyTopics:['Familie']},
{id:'a1-present-actions',title:'Alltag im Präsens',domain:'grammar',prerequisites:['a1-introduce-self'],outcomes:['häufige Tätigkeiten im Präsens ausdrücken','Personenformen unterscheiden'],grammarTargets:['present-singular','present-plural','verb-person'],vocabularyTopics:['Alltag','Arbeit']},
{id:'a1-dual-core',title:'Dual verstehen und verwenden',domain:'grammar',prerequisites:['a1-family','a1-present-actions'],outcomes:['Singular, Dual und Plural unterscheiden','häufige Verben in der 1. Person Dual verwenden','dva und dve grundlegend unterscheiden'],grammarTargets:['dual-vs-plural','dual-verbs','numeral-gender'],vocabularyTopics:['Personen','Zahlen']},
{id:'a1-food',title:'Essen und Trinken',domain:'communication',prerequisites:['a1-present-actions'],outcomes:['einfache Speisen und Getränke benennen','Wünsche ausdrücken','einfach bestellen'],grammarTargets:['accusative-basic','zeleti-present'],vocabularyTopics:['Essen','Getränke','Restaurant']},
{id:'a1-location',title:'Wo bin ich?',domain:'grammar',prerequisites:['a1-present-actions'],outcomes:['einfache Orte angeben','v + Lokativ in häufigen Wendungen verwenden'],grammarTargets:['location-static-v-locative'],vocabularyTopics:['Orte','Stadt']},
{id:'a1-direction',title:'Wohin gehe oder fahre ich?',domain:'grammar',prerequisites:['a1-location'],outcomes:['Richtungen und Ziele ausdrücken','Ort und Richtung unterscheiden'],grammarTargets:['direction-v-accusative','iti-present','peljati-se-present'],vocabularyTopics:['Verkehr','Reise']},
{id:'a1-daily-routine',title:'Tagesablauf',domain:'speaking',prerequisites:['a1-present-actions','a1-numbers-time'],outcomes:['einen einfachen Tagesablauf beschreiben','Zeitangaben mit bekannten Tätigkeiten kombinieren'],vocabularyTopics:['Alltag','Zeit']},
{id:'a1-shopping',title:'Einkaufen',domain:'communication',prerequisites:['a1-food','a1-numbers-time'],outcomes:['nach einfachen Produkten fragen','Mengen und Preise grundlegend verstehen'],grammarTargets:['accusative-basic','numeral-gender'],vocabularyTopics:['Einkaufen','Lebensmittel']},
{id:'a1-travel',title:'Unterwegs und Reisen',domain:'communication',prerequisites:['a1-direction','a1-numbers-time'],outcomes:['Ziel und Verkehrsmittel nennen','einfache Reiseinformationen verstehen'],grammarTargets:['direction-v-accusative','instrumental-basic'],vocabularyTopics:['Reise','Verkehr']},
{id:'a1-negation',title:'Verneinen und Nicht-Haben',domain:'grammar',prerequisites:['a1-present-actions','a1-food'],outcomes:['einfache Aussagen verneinen','nimam mit häufigen Genitivformen verwenden'],grammarTargets:['negation-basic','nimam-genitive'],vocabularyTopics:['Alltag']},
{id:'a1-listening-sentences',title:'Kurze Sätze verstehen',domain:'listening',prerequisites:['a1-daily-routine','a1-location'],outcomes:['bekannte Wörter in gesprochenen Sätzen erkennen','Kernaussage kurzer Äußerungen verstehen']},
{id:'a1-reading-mini',title:'Kurze Alltagstexte verstehen',domain:'reading',prerequisites:['a1-listening-sentences','a1-food','a1-direction'],outcomes:['kurze A1-Texte mit überwiegend bekanntem Wortschatz verstehen','einfache Verständnisfragen beantworten']},
{id:'a1-conversation',title:'Kurzes Alltagsgespräch führen',domain:'speaking',prerequisites:['a1-food','a1-location','a1-direction','a1-dual-core'],outcomes:['mehrere zusammenhängende einfache Antworten geben','Rückfragen in bekannten Situationen verstehen','mit Hilfen Gesprächsprobleme lösen']},
{id:'a1-transfer',title:'Bekannte Strukturen übertragen',domain:'communication',prerequisites:['a1-conversation','a1-reading-mini','a1-negation'],outcomes:['bekannte Grammatik in neuen einfachen Kontexten anwenden','nicht nur auswendig gelernte Beispielsätze reproduzieren']}
]

export function getA1Skill(id:string){return A1_SKILL_GRAPH.find(s=>s.id===id)}
export function getA1UnlockedSkills(completed:Set<string>){return A1_SKILL_GRAPH.filter(s=>s.prerequisites.every(p=>completed.has(p)))}
export function auditA1SkillGraph(){const ids=new Set(A1_SKILL_GRAPH.map(s=>s.id));return A1_SKILL_GRAPH.flatMap(s=>s.prerequisites.filter(p=>!ids.has(p)).map(p=>`${s.id}: missing prerequisite ${p}`))}
