import { enrichExercises } from '@/lib/curriculum-metadata'
import { MASTERY_THRESHOLDS } from '@/lib/learner-status'
import { Exercise, MasteryItem, UserProgress, Vocabulary } from '@/types'
import { buildTransferExercise, injectDueTransfer } from '@/lib/transfer-practice'

export type AdaptiveActionKind='review'|'strengthen'|'new-content'|'speaking'
export type AdaptiveRecommendation={kind:AdaptiveActionKind;title:string;reason:string;priority:number;lessonId?:number;focusKeys:string[];exerciseIds:string[]}
const WEAK_THRESHOLD=.58,MIN_ATTEMPTS_FOR_WEAK=2
function weakItems(progress:UserProgress){return Object.values(progress.mastery||{}).filter(m=>m.attempts>=MIN_ATTEMPTS_FOR_WEAK&&m.score<WEAK_THRESHOLD).sort((a,b)=>a.score-b.score||b.attempts-a.attempts)}
function exerciseKeys(ex:Exercise){return [...(ex.vocabularyIds||[]).map(id=>`vocab:${id}`),...(ex.grammarRuleIds||[]).map(id=>`grammar:${id}`),...(ex.skillTargets||[]).map(id=>`skill:${id}`),ex.id]}
function exercisesForMastery(items:MasteryItem[],exercises:Exercise[]){const keys=new Set(items.map(x=>x.key));return exercises.filter(ex=>exerciseKeys(ex).some(k=>keys.has(k)))}
function unique<T>(items:T[]){return Array.from(new Set(items))}
function fluencyConcern(progress:UserProgress){const recent=(progress.recentAttempts||[]).slice(-12);if(recent.length<4)return false;const correct=recent.filter(x=>x.correct);if(correct.length<3)return false;const slow=correct.filter(x=>x.responseMs>30_000).length,helped=correct.filter(x=>x.hintsUsed>0).length;return slow+helped>=Math.ceil(correct.length/2)}
function newWordBudget(progress:UserProgress){const pace=progress.preferences?.pace||'normal';return pace==='ruhig'?2:pace==='intensiv'?4:3}

export function buildAdaptiveRecommendation(progress:UserProgress,rawExercises:Exercise[],vocabulary:Vocabulary[],activeLesson:number,now=Date.now()):AdaptiveRecommendation{
 const exercises=enrichExercises(rawExercises),dueIds=progress.reviews.filter(r=>r.dueAt<=now).map(r=>r.key)
 if(dueIds.length){const dueSet=new Set(dueIds),matching=exercises.filter(e=>exerciseKeys(e).some(k=>dueSet.has(k)));return {kind:'review',title:'Fällige Wiederholungen',reason:`${dueIds.length} Lernziele sind jetzt fällig. Erst festigen, dann Neues lernen.`,priority:100,focusKeys:dueIds,exerciseIds:matching.map(e=>e.id).slice(0,10)}}
 const attemptCount=progress.recentAttempts?.length||0,viableTransfer=(progress.transferQueue||[]).find(item=>buildTransferExercise(item,exercises,attemptCount))
 if(viableTransfer)return {kind:'strengthen',title:'Grammatik auf neue Beispiele übertragen',reason:'Nach einem Grammatikfehler prüft die App mit einem anderen Satz, ob du die Regel wirklich verstanden hast.',priority:90,focusKeys:[`grammar:${viableTransfer.grammarRuleId}`],exerciseIds:[]}
 const weakGrammar=weakItems(progress).filter(x=>x.kind==='grammar');if(weakGrammar.length){const top=weakGrammar.slice(0,3),deck=exercisesForMastery(top,exercises),w=top[0];return {kind:'strengthen',title:'Grammatik gezielt festigen',reason:`Hier besteht noch Unsicherheit (${Math.round(w.score*100)} % Sicherheit).`,priority:85,focusKeys:top.map(x=>x.key),exerciseIds:unique(deck.map(e=>e.id)).slice(0,10)}}
 const weakVocab=weakItems(progress).filter(x=>x.kind==='vocabulary');if(weakVocab.length){const top=weakVocab.slice(0,3),deck=exercisesForMastery(top,exercises),w=top[0];return {kind:'strengthen',title:'Wortschatz gezielt festigen',reason:`Einige Wörter sind noch nicht stabil (${Math.round(w.score*100)} % Sicherheit).`,priority:80,focusKeys:top.map(x=>x.key),exerciseIds:unique(deck.map(e=>e.id)).slice(0,10)}}
 const production=progress.mastery?.['skill:production'],recognition=progress.mastery?.['skill:recognition'];if((recognition?.attempts||0)>=3&&(!production||production.score+0.12<(recognition.score||0)))return {kind:'speaking',title:'Mehr selbst produzieren',reason:'Erkennen klappt besser als selbst formulieren. Deshalb ist jetzt aktive Produktion sinnvoll.',priority:75,focusKeys:['skill:production'],exerciseIds:exercises.filter(e=>e.skillTargets?.includes('production')).map(e=>e.id).slice(0,8)}
 const listening=progress.mastery?.['skill:listening'];if((listening?.attempts||0)>=2&&listening.score<MASTERY_THRESHOLDS.learning)return {kind:'strengthen',title:'Hörverständnis festigen',reason:'Beim Hören brauchst du noch etwas Unterstützung.',priority:70,focusKeys:['skill:listening'],exerciseIds:exercises.filter(e=>e.skillTargets?.includes('listening')).map(e=>e.id).slice(0,8)}
 const speaking=progress.mastery?.['skill:speaking'];if((speaking?.attempts||0)>=2&&speaking.score<MASTERY_THRESHOLDS.learning)return {kind:'speaking',title:'Sprechen festigen',reason:'Aktives Sprechen ist aktuell noch unsicher.',priority:68,focusKeys:['skill:speaking'],exerciseIds:[]}
 if(fluencyConcern(progress))return {kind:'strengthen',title:'Sicherer und flüssiger antworten',reason:'Mehrere richtige Antworten brauchten zuletzt viel Zeit oder einen Hinweis.',priority:65,focusKeys:['skill:fluency'],exerciseIds:exercises.filter(e=>e.type!=='choice').map(e=>e.id).slice(0,8)}
 const budget=newWordBudget(progress),lessonWords=vocabulary.filter(v=>v.lesson===activeLesson),unseen=lessonWords.filter(v=>!progress.introducedWords.includes(v.id));return {kind:'new-content',title:`Weiter mit Lektion ${activeLesson}`,reason:unseen.length?`${Math.min(budget,unseen.length)} neue Wörter sind für den nächsten Lernblock vorgesehen.`:'Die neuen Wörter sind eingeführt. Jetzt festigst du sie im Lektionenablauf.',priority:50,lessonId:activeLesson,focusKeys:unseen.slice(0,budget).map(v=>`vocab:${v.id}`),exerciseIds:exercises.filter(e=>e.lesson===activeLesson).map(e=>e.id).slice(0,8)}
}

export function buildAdaptiveReviewDeck(progress:UserProgress,rawExercises:Exercise[],limit=10,now=Date.now()):Exercise[]{const exercises=enrichExercises(rawExercises),due=new Set(progress.reviews.filter(r=>r.dueAt<=now).map(r=>r.key)),mistakes=new Set([...progress.mistakes].sort((a,b)=>b.count-a.count).map(m=>m.key)),weak=weakItems(progress).slice(0,5),weakExercises=exercisesForMastery(weak,exercises);const scored=exercises.map((ex,index)=>{let score=0;if(exerciseKeys(ex).some(k=>due.has(k)))score+=100;if(mistakes.has(ex.id))score+=60;if(weakExercises.some(w=>w.id===ex.id))score+=45;if((ex.vocabularyIds||[]).some(id=>(progress.mastery?.[`vocab:${id}`]?.score??1)<WEAK_THRESHOLD))score+=20;if((ex.grammarRuleIds||[]).some(id=>(progress.mastery?.[`grammar:${id}`]?.score??1)<WEAK_THRESHOLD))score+=25;return {ex,score,index}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index);let chosen=unique(scored.map(x=>x.ex.id)).map(id=>exercises.find(e=>e.id===id)!).slice(0,limit);if(chosen.length<Math.min(4,limit))chosen=[...chosen,...exercises.filter(e=>!chosen.some(c=>c.id===e.id)).slice(0,limit-chosen.length)];const transfer=injectDueTransfer(chosen,progress.transferQueue||[],exercises,progress.recentAttempts?.length||0);return transfer.exercises.slice(0,limit)}
