'use client'
import { exercises as seedExercises } from '@/data/seed'
import { enrichExercises } from '@/lib/curriculum-metadata'
import { mergeExamHistory } from '@/lib/exam-history'
import { defaultPreferences } from '@/lib/storage'
import { MasteryItem, ReviewItem, UserProgress } from '@/types'
const DEFAULT_URL='https://jzukiyzyrzompanpsvdu.supabase.co'
const DEFAULT_PUBLISHABLE_KEY='sb_publishable_X3l5xnodb67J9cY57WxEWQ_7Rfgo8uZ'
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL||DEFAULT_URL,KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||DEFAULT_PUBLISHABLE_KEY,SESSION_KEY='slovensko-cloud-session-v1'
const curriculumExercises=enrichExercises(seedExercises)
export type CloudSession={access_token:string;refresh_token:string;expires_at?:number;user:{id:string;email?:string}}
export type CloudProfile={id:string;user_id:string;name:string;approximate_level:string}
function configured(){return Boolean(URL&&KEY)}
function headers(token?:string){return {apikey:KEY,Authorization:`Bearer ${token||KEY}`,'Content-Type':'application/json'}}
function friendlyError(status:number,data:any){const raw=String(data?.msg||data?.message||data?.error_description||data?.error||'').toLowerCase();if(status===400&&(raw.includes('invalid login')||raw.includes('credentials')))return 'E-Mail oder Passwort ist nicht korrekt.';if(raw.includes('email not confirmed'))return 'Bitte bestätige zuerst deine E-Mail-Adresse.';if(raw.includes('already registered')||raw.includes('already been registered'))return 'Für diese E-Mail-Adresse gibt es bereits ein Konto.';if(status===401)return 'Deine Sitzung ist abgelaufen. Bitte melde dich erneut an.';if(status>=500)return 'Der Synchronisationsdienst ist gerade nicht erreichbar. Du kannst lokal weiterlernen.';return data?.message||data?.error_description||'Cloud-Anfrage fehlgeschlagen.'}
async function request(url:string,init?:RequestInit){let res:Response;try{res=await fetch(url,init)}catch{throw new Error('Keine Verbindung. Dein Lernfortschritt wird zunächst auf diesem Gerät gespeichert.')}const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(friendlyError(res.status,data));return data}
export function cloudConfigured(){return configured()}
export function loadSession():CloudSession|null{if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
export function saveSession(session:CloudSession|null){if(typeof window==='undefined')return;session?localStorage.setItem(SESSION_KEY,JSON.stringify(session)):localStorage.removeItem(SESSION_KEY)}
export async function signIn(email:string,password:string):Promise<CloudSession>{if(!configured())throw new Error('Cloud-Synchronisation ist noch nicht konfiguriert.');const data=await request(`${URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:headers(),body:JSON.stringify({email,password})}),session={...data,expires_at:Date.now()+Number(data.expires_in||3600)*1000} as CloudSession;saveSession(session);return session}
export async function signUp(email:string,password:string):Promise<CloudSession|null>{if(!configured())throw new Error('Cloud-Synchronisation ist noch nicht konfiguriert.');const data=await request(`${URL}/auth/v1/signup`,{method:'POST',headers:headers(),body:JSON.stringify({email,password})});if(!data.access_token)return null;const session={...data,expires_at:Date.now()+Number(data.expires_in||3600)*1000} as CloudSession;saveSession(session);return session}
export async function signOut(){const s=loadSession();if(s)try{await request(`${URL}/auth/v1/logout`,{method:'POST',headers:headers(s.access_token)})}catch{}saveSession(null)}
export async function ensureFreshSession(session:CloudSession):Promise<CloudSession>{if(!session.expires_at||session.expires_at-Date.now()>60_000)return session;try{const data=await request(`${URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:headers(),body:JSON.stringify({refresh_token:session.refresh_token})}),next={...data,expires_at:Date.now()+Number(data.expires_in||3600)*1000} as CloudSession;saveSession(next);return next}catch(e){saveSession(null);throw e}}
export async function ensureProfile(session:CloudSession):Promise<CloudProfile>{const s=await ensureFreshSession(session),existing=await request(`${URL}/rest/v1/learner_profiles?select=id,user_id,name,approximate_level&client_profile_id=eq.default&limit=1`,{headers:headers(s.access_token)});if(existing[0])return existing[0];const name=s.user.email?.split('@')[0]||'Lernprofil',created=await request(`${URL}/rest/v1/learner_profiles`,{method:'POST',headers:{...headers(s.access_token),Prefer:'return=representation'},body:JSON.stringify({user_id:s.user.id,client_profile_id:'default',name,start_mode:'adaptive',approximate_level:'A1',onboarding_completed:true,placement_completed:false})});return created[0]}
export async function loadCloudProgress(session:CloudSession,profileId:string):Promise<UserProgress|null>{const s=await ensureFreshSession(session),rows=await request(`${URL}/rest/v1/learner_states?select=state&profile_id=eq.${encodeURIComponent(profileId)}&limit=1`,{headers:headers(s.access_token)});return rows[0]?.state||null}
async function syncAttempts(session:CloudSession,profileId:string,progress:UserProgress){const attempts=(progress.recentAttempts||[]).slice(-150);if(!attempts.length)return;const rows=attempts.map((a,index)=>{const ex=curriculumExercises.find(e=>e.id===a.exerciseId);return {user_id:session.user.id,id:`${a.exerciseId}-${a.occurredAt}`,profile_id:profileId,exercise_id:a.exerciseId,learning_goal_ids:[...(a.vocabularyIds||ex?.vocabularyIds||[]).map(id=>`vocab:${id}`),...(a.grammarRuleIds||ex?.grammarRuleIds||[]).map(id=>`grammar:${id}`)],input_mode:(a.skillTargets||ex?.skillTargets||[]).join(',')||ex?.type||'unknown',answer:null,correct:a.correct,mistake_category:a.correct?null:'incorrect',response_ms:a.responseMs,hints_used:a.hintsUsed,attempt_number:index+1,occurred_at:new Date(a.occurredAt).toISOString()}});await request(`${URL}/rest/v1/exercise_attempts?on_conflict=user_id,id`,{method:'POST',headers:{...headers(session.access_token),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
export async function saveCloudProgress(session:CloudSession,profileId:string,progress:UserProgress){const s=await ensureFreshSession(session),now=Date.now(),payload={...progress,updatedAt:Math.max(progress.updatedAt||0,now),lastSyncedAt:now},current=await request(`${URL}/rest/v1/learner_states?select=id,revision&profile_id=eq.${encodeURIComponent(profileId)}&limit=1`,{headers:headers(s.access_token)});if(current[0])await request(`${URL}/rest/v1/learner_states?id=eq.${current[0].id}`,{method:'PATCH',headers:{...headers(s.access_token),Prefer:'return=representation'},body:JSON.stringify({state:payload,revision:Number(current[0].revision||0)+1,updated_at:new Date(now).toISOString()})});else await request(`${URL}/rest/v1/learner_states`,{method:'POST',headers:{...headers(s.access_token),Prefer:'return=representation'},body:JSON.stringify({user_id:s.user.id,profile_id:profileId,state:payload,revision:1})});await syncAttempts(s,profileId,payload);return payload}
function newerMastery(a?:MasteryItem,b?:MasteryItem){if(!a)return b;if(!b)return a;return (b.lastSeen||0)>(a.lastSeen||0)?b:a}
function newerReview(a?:ReviewItem,b?:ReviewItem){if(!a)return b;if(!b)return a;return (b.updatedAt||0)>(a.updatedAt||0)?b:a}
export function mergeProgress(local:UserProgress,cloud:UserProgress):UserProgress{
 const localReset=local.resetAt||0,cloudReset=cloud.resetAt||0;if(localReset>(cloud.updatedAt||0))return {...local,lastSyncedAt:Math.max(local.lastSyncedAt||0,cloud.lastSyncedAt||0)};if(cloudReset>(local.updatedAt||0))return {...cloud,preferences:{...defaultPreferences,...cloud.preferences}}
 const union=(a:string[]=[],b:string[]=[])=>Array.from(new Set([...a,...b])),lessons=union((local.completedLessons||[]).map(String),(cloud.completedLessons||[]).map(String)).map(Number),mistakeMap=new Map<string,any>(),reviewMap=new Map<string,ReviewItem>(),masteryKeys=new Set([...Object.keys(local.mastery||{}),...Object.keys(cloud.mastery||{})]),mastery:Record<string,MasteryItem>={}
 ;[...(local.mistakes||[]),...(cloud.mistakes||[])].forEach(m=>{const old=mistakeMap.get(m.key);if(!old||m.count>old.count||m.lastSeen>old.lastSeen)mistakeMap.set(m.key,m)})
 ;[...(local.reviews||[]),...(cloud.reviews||[])].forEach(r=>reviewMap.set(r.key,newerReview(reviewMap.get(r.key),r)!))
 masteryKeys.forEach(k=>{const chosen=newerMastery(local.mastery?.[k],cloud.mastery?.[k]);if(chosen)mastery[k]=chosen})
 const attempts=[...(local.recentAttempts||[]),...(cloud.recentAttempts||[])].sort((a,b)=>a.occurredAt-b.occurredAt).filter((x,i,a)=>i===0||`${x.exerciseId}:${x.occurredAt}`!==`${a[i-1].exerciseId}:${a[i-1].occurredAt}`).slice(-150),transfers=[...(local.transferQueue||[]),...(cloud.transferQueue||[])].filter((x,i,a)=>a.findIndex(y=>y.sourceExerciseId===x.sourceExerciseId&&y.grammarRuleId===x.grammarRuleId)===i),localPrefsNewer=(local.preferencesUpdatedAt||0)>=(cloud.preferencesUpdatedAt||0),preferences={...defaultPreferences,...(localPrefsNewer?cloud.preferences:local.preferences),...(localPrefsNewer?local.preferences:cloud.preferences)}
 return {...local,...cloud,completedLessons:lessons,introducedWords:union(local.introducedWords,cloud.introducedWords),introducedGrammarRules:union(local.introducedGrammarRules,cloud.introducedGrammarRules),introducedVerbForms:union(local.introducedVerbForms,cloud.introducedVerbForms),wordsLearned:union(local.wordsLearned,cloud.wordsLearned),secureWords:union(local.secureWords,cloud.secureWords),mistakes:Array.from(mistakeMap.values()),reviews:Array.from(reviewMap.values()),streak:Math.max(local.streak||0,cloud.streak||0),speakingMinutes:Math.max(local.speakingMinutes||0,cloud.speakingMinutes||0),listeningMinutes:Math.max(local.listeningMinutes||0,cloud.listeningMinutes||0),mastery,recentAttempts:attempts,transferQueue:transfers,examHistory:mergeExamHistory(local.examHistory,cloud.examHistory),preferences,preferencesUpdatedAt:Math.max(local.preferencesUpdatedAt||0,cloud.preferencesUpdatedAt||0),updatedAt:Math.max(local.updatedAt||0,cloud.updatedAt||0),resetAt:Math.max(localReset,cloudReset)||undefined,lastSyncedAt:Math.max(local.lastSyncedAt||0,cloud.lastSyncedAt||0)}
}
