export type ConversationTopic='smalltalk'|'restaurant'|'travel'|'shopping'|'hotel'|'family'
export type ConversationStep={id:string;prompt:string;translation:string;intent:string;acceptedPatterns:string[];hint:string;grammarTargets:string[];vocabulary:string[]}
export type ConversationScenario={id:ConversationTopic;label:string;level:'A1';goal:string;grammarTargets:string[];vocabulary:string[];steps:ConversationStep[]}

export const CONVERSATION_CURRICULUM:ConversationScenario[]=[
{id:'smalltalk',label:'Smalltalk',level:'A1',goal:'Ort und einfache Tätigkeit nennen',grammarTargets:['location-static-v-locative','biti-present','present-singular'],vocabulary:['doma','danes','delati','kuhati'],steps:[
{id:'location',prompt:'Živjo! Kje si zdaj?',translation:'Hallo! Wo bist du gerade?',intent:'location',acceptedPatterns:['sem doma','sem v ','zdaj sem'],hint:'Sem doma. / Sem v …',grammarTargets:['location-static-v-locative'],vocabulary:['doma']},
{id:'activity',prompt:'Kaj delaš tam?',translation:'Was machst du dort?',intent:'activity',acceptedPatterns:['delam','kuham','počivam','jem','pijem'],hint:'Delam … / Kuham … / Počivam.',grammarTargets:['present-singular'],vocabulary:['delati','kuhati']},
{id:'next',prompt:'Kaj boš delal potem?',translation:'Was machst du danach?',intent:'next-action',acceptedPatterns:['grem','ostanem','delam','kuham'],hint:'Potem grem … / Potem ostanem doma.',grammarTargets:['direction-v-accusative'],vocabulary:['potem','iti']}]},
{id:'restaurant',label:'Restaurant',level:'A1',goal:'Getränk und Essen bestellen',grammarTargets:['accusative-basic','zeleti-present'],vocabulary:['voda','kava','čaj','juha','pica'],steps:[
{id:'drink',prompt:'Dober dan. Kaj želite piti?',translation:'Guten Tag. Was möchten Sie trinken?',intent:'order-drink',acceptedPatterns:['želim ','pil bi','pila bi','vodo','kavo','čaj'],hint:'Želim vodo. / Pil bi kavo.',grammarTargets:['zeleti-present','accusative-basic'],vocabulary:['voda','kava','čaj']},
{id:'food',prompt:'Kaj želite jesti?',translation:'Was möchten Sie essen?',intent:'order-food',acceptedPatterns:['želim ','jedel bi','jedla bi','juho','pico'],hint:'Želim juho. / Jedel bi pico.',grammarTargets:['accusative-basic'],vocabulary:['juha','pica']},
{id:'more',prompt:'Želite še kaj?',translation:'Möchten Sie noch etwas?',intent:'more',acceptedPatterns:['ne hvala','da','še ','želim'],hint:'Ne, hvala. / Da, še …',grammarTargets:['negation-basic'],vocabulary:['hvala']}]},
{id:'travel',label:'Unterwegs',level:'A1',goal:'Ziel, Verkehrsmittel und Begleitung nennen',grammarTargets:['direction-v-accusative','peljati-se-present'],vocabulary:['domov','avto','vlak','danes'],steps:[
{id:'destination',prompt:'Kam greš danes?',translation:'Wohin gehst oder fährst du heute?',intent:'destination',acceptedPatterns:['grem ','peljem se ','domov'],hint:'Grem domov. / Grem v …',grammarTargets:['direction-v-accusative'],vocabulary:['domov']},
{id:'transport',prompt:'Kako greš tja?',translation:'Wie kommst du dorthin?',intent:'transport',acceptedPatterns:['z avtom','z vlakom','peš','peljem se'],hint:'Grem z avtom. / Peljem se z vlakom.',grammarTargets:['instrumental-basic'],vocabulary:['avto','vlak']},
{id:'with',prompt:'S kom greš?',translation:'Mit wem gehst oder fährst du?',intent:'companion',acceptedPatterns:['sam','s prijateljem','z družino','z '],hint:'Grem sam. / Grem s prijateljem.',grammarTargets:['instrumental-basic'],vocabulary:['prijatelj','družina']}]},
{id:'shopping',label:'Einkaufen',level:'A1',goal:'Produkt, Menge und einfache Präferenz ausdrücken',grammarTargets:['accusative-basic','numeral-gender'],vocabulary:['iskati','kruh','voda','dva','dve'],steps:[
{id:'product',prompt:'Dober dan. Kaj iščete?',translation:'Guten Tag. Was suchen Sie?',intent:'product',acceptedPatterns:['iščem '],hint:'Iščem …',grammarTargets:['accusative-basic'],vocabulary:['iskati']},
{id:'quantity',prompt:'Koliko želite?',translation:'Wie viel möchten Sie?',intent:'quantity',acceptedPatterns:['en ','eno ','dva ','dve ','tri '],hint:'Eno … / Dva … / Dve …',grammarTargets:['numeral-gender','dual-vs-plural'],vocabulary:['dva','dve']}]},
{id:'hotel',label:'Hotel',level:'A1',goal:'Zimmer und einfache Reisedaten nennen',grammarTargets:['imeti-present','accusative-basic'],vocabulary:['soba','danes','jutri'],steps:[{id:'room',prompt:'Dober dan. Imate rezervacijo?',translation:'Guten Tag. Haben Sie eine Reservierung?',intent:'reservation',acceptedPatterns:['da','imam','ne'],hint:'Da, imam rezervacijo.',grammarTargets:['imeti-present'],vocabulary:['imeti']},{id:'nights',prompt:'Za koliko noči?',translation:'Für wie viele Nächte?',intent:'nights',acceptedPatterns:['eno','dve','tri'],hint:'Za dve noči.',grammarTargets:['numeral-gender'],vocabulary:['dve']}]},
{id:'family',label:'Familie',level:'A1',goal:'Familienmitglieder beschreiben und Dual verwenden',grammarTargets:['imeti-present','dual-vs-plural','numeral-gender'],vocabulary:['brat','sestra','dva','dve'],steps:[{id:'siblings',prompt:'Imaš brata ali sestro?',translation:'Hast du einen Bruder oder eine Schwester?',intent:'siblings',acceptedPatterns:['imam','nimam','brata','sestro'],hint:'Imam brata. / Imam sestro.',grammarTargets:['imeti-present'],vocabulary:['brat','sestra']},{id:'count',prompt:'Koliko bratov ali sester imaš?',translation:'Wie viele Brüder oder Schwestern hast du?',intent:'count-family',acceptedPatterns:['imam dva','imam dve','imam enega','imam eno'],hint:'Imam dva brata. / Imam dve sestri.',grammarTargets:['dual-vs-plural','numeral-gender'],vocabulary:['dva','dve','brat','sestra']}]}
]

export function conversationScenario(id:ConversationTopic){return CONVERSATION_CURRICULUM.find(s=>s.id===id)??CONVERSATION_CURRICULUM[0]}
export function conversationStepForPrompt(topic:ConversationTopic,prompt:string){const s=conversationScenario(topic);const p=prompt.trim().toLowerCase();return s.steps.find(step=>step.prompt.toLowerCase()===p)||s.steps.find(step=>p.includes(step.prompt.toLowerCase().replace(/[?!.,]/g,'')))}
export function nextConversationStep(topic:ConversationTopic,currentStepId:string){const s=conversationScenario(topic);const i=s.steps.findIndex(step=>step.id===currentStepId);return i>=0?s.steps[Math.min(i+1,s.steps.length-1)]:s.steps[0]}
export function scenarioForWeakTargets(weakTargets:string[]=[]){return [...CONVERSATION_CURRICULUM].sort((a,b)=>b.grammarTargets.filter(t=>weakTargets.includes(t)).length-a.grammarTargets.filter(t=>weakTargets.includes(t)).length)[0]}
